import { useState } from 'react'
import { ArrowLeft, ArrowRight, Eye, EyeOff, Headphones, KeyRound, Mail, ShieldCheck } from 'lucide-react'
import { Brand, PageContainer } from './Brand'
import LanguagePicker from './LanguagePicker'
import { signInDj, supabaseEnabled } from '../lib/supabase'
import { useLanguage } from '../lib/i18n'

export default function DjLogin({ onLogin, onBack }) {
  const { t } = useLanguage(); const [email, setEmail] = useState(''); const [code, setCode] = useState(''); const [show, setShow] = useState(false); const [error, setError] = useState('')
  async function submit(e) {
    e.preventDefault(); setError('')
    try { if (!supabaseEnabled) throw new Error('SUPABASE_REQUIRED'); onLogin(await signInDj(email, code)) }
    catch (err) { setError(err?.message === 'SUPABASE_REQUIRED' ? t('supabaseRequired') : t('loginError')) }
  }
  return <div className="min-h-screen bg-ink bg-grid"><PageContainer className="flex min-h-screen flex-col"><div className="flex items-center justify-between"><Brand /><div className="flex items-center gap-2"><LanguagePicker /><button onClick={onBack} className="btn-secondary px-3 py-2 text-sm"><ArrowLeft size={16} /> {t('back')}</button></div></div><div className="flex flex-1 items-center justify-center py-14"><div className="w-full max-w-md"><div className="mb-8 text-center"><div className="mx-auto mb-5 grid h-16 w-16 place-items-center rounded-3xl bg-violet/20 text-violet-200"><Headphones size={30} /></div><p className="eyebrow text-violet-200">{t('djAccess')}</p><h1 className="mt-3 font-display text-4xl font-bold tracking-tight sm:text-5xl">{t('djHeading')}</h1><p className="mt-4 text-sm leading-6 text-white/55">{t('djDescription')}</p></div><form onSubmit={submit} className="glass rounded-[2rem] p-5 sm:p-7"><label className="mb-2 block text-sm font-semibold text-white/75">{t('email')}</label><div className="relative"><Mail size={18} className="absolute left-4 top-1/2 -translate-y-1/2 text-white/35" /><input autoFocus required type="email" value={email} onChange={(e) => { setEmail(e.target.value); setError('') }} className="input-dark pl-11" placeholder="dj@ejemplo.com" autoComplete="username" /></div><label className="mb-2 mt-4 block text-sm font-semibold text-white/75">{t('accessCode')}</label><div className="relative"><KeyRound size={18} className="absolute left-4 top-1/2 -translate-y-1/2 text-white/35" /><input required type={show ? 'text' : 'password'} value={code} onChange={(e) => { setCode(e.target.value); setError('') }} className="input-dark pl-11 pr-12" placeholder="Código personal" autoComplete="one-time-code" /><button type="button" onClick={() => setShow(!show)} className="absolute right-3 top-1/2 -translate-y-1/2 rounded-lg p-1.5 text-white/35 hover:text-white" aria-label={show ? 'Ocultar código' : 'Mostrar código'}>{show ? <EyeOff size={18} /> : <Eye size={18} />}</button></div>{error && <p className="mt-3 rounded-xl border border-red-400/20 bg-red-400/10 px-3 py-2 text-sm text-red-200">{error}</p>}<button className="btn-primary mt-5 w-full">{t('enter')} <ArrowRight size={18} /></button><div className="mt-5 flex items-center gap-2 text-xs text-white/35"><ShieldCheck size={14} className="text-violet-300" /> {t('codeHint')}</div></form></div></div></PageContainer></div>
}
