import { ArrowRight, Headphones, Heart, Mic2, PartyPopper, ShieldCheck, Sparkles, Users } from 'lucide-react'
import { Brand, PageContainer } from './Brand'
import LanguagePicker from './LanguagePicker'
import { useLanguage } from '../lib/i18n'

function RoleCard({ icon: Icon, title, copy, action, accent, onClick, features, label }) {
  return <button onClick={onClick} className={`group glass relative overflow-hidden rounded-[2rem] p-6 text-left transition hover:-translate-y-1 hover:border-white/25 sm:p-8 ${accent === 'violet' ? 'hover:shadow-violet' : 'hover:shadow-glow'}`}>
    <div className={`absolute -right-12 -top-12 h-36 w-36 rounded-full blur-3xl ${accent === 'violet' ? 'bg-violet/30' : 'bg-neon/20'}`} />
    <div className="relative"><div className={`mb-7 grid h-14 w-14 place-items-center rounded-2xl ${accent === 'violet' ? 'bg-violet/20 text-violet-200' : 'bg-neon/15 text-neon'}`}><Icon size={28} /></div><p className="mb-2 text-xs font-bold uppercase tracking-[.18em] text-white/45">{label}</p><h2 className="font-display text-2xl font-bold sm:text-3xl">{title}</h2><p className="mt-3 max-w-sm text-sm leading-6 text-white/60">{copy}</p><div className="mt-7 flex flex-wrap gap-2">{features.map((feature) => <span key={feature} className="rounded-full border border-white/10 bg-white/[.04] px-3 py-1.5 text-xs text-white/65">{feature}</span>)}</div><div className="mt-8 flex items-center gap-2 font-semibold text-white group-hover:text-neon"><span className="fire-text font-bold">{action}</span><ArrowRight size={18} className="transition group-hover:translate-x-1" /></div></div>
  </button>
}

export default function HomeScreen({ onAttendee, onDj }) {
  const { t } = useLanguage()
  return <div className="party-page min-h-screen bg-ink bg-grid"><PageContainer className="flex min-h-screen flex-col"><div className="flex items-center justify-between"><Brand /><div className="flex items-center gap-2"><LanguagePicker /><span className="hidden rounded-full border border-neon/20 bg-neon/10 px-3 py-1.5 text-xs font-semibold text-neon sm:block">{t('homeTagline')}</span></div></div><div className="flex flex-1 flex-col justify-center py-14 sm:py-20"><div className="max-w-3xl"><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[.04] px-3 py-1.5 text-xs font-semibold text-white/60"><Sparkles size={14} className="text-neon" /> {t('homeBadge')}</div><h1 className="font-display text-5xl font-bold leading-[.98] tracking-[-.06em] sm:text-7xl">{t('homeTitle')}<br /><span className="text-neon">{t('homeTitleAccent')}</span></h1><p className="mt-6 max-w-xl text-base leading-7 text-white/55 sm:text-lg">{t('homeCopy')}</p></div><div className="home-visual party-banner mb-8 h-40 rounded-[2rem] sm:h-48" aria-label={t('liveDescription')}><div className="party-banner__surface party-banner__surface--waves" aria-hidden="true" /><div className="absolute inset-0 z-10 flex items-center px-6 sm:px-8"><div><p className="eyebrow">{t('liveBadge')}</p><p className="mt-2 max-w-md font-display text-xl font-bold text-white sm:text-2xl">{t('liveDescription')}</p></div></div></div><div className="mt-12 grid gap-5 md:grid-cols-2"><RoleCard icon={Users} label={t('publicLabel')} title={t('attendeeTitle')} copy={t('attendeeCopy')} action={t('attendeeAction')} accent="lime" features={[t('search'), t('vote'), t('dedicate')]} onClick={onAttendee} /><RoleCard icon={Headphones} label={t('organization')} title={t('djTitle')} copy={t('djCopy')} action={t('djAction')} accent="violet" features={[t('liveQueue'), t('playback'), t('createEvents')]} onClick={onDj} /></div><div className="mt-8 flex flex-wrap items-center gap-x-6 gap-y-3 text-xs text-white/40"><span className="flex items-center gap-2"><Heart size={14} className="text-neon" /> {t('queueLikes')}</span><span className="flex items-center gap-2"><Mic2 size={14} className="text-violet-300" /> {t('dedicationMoment')}</span><span className="flex items-center gap-2"><PartyPopper size={14} className="text-amber-300" /> {t('madeForParties')}</span></div></div><div className="flex items-center gap-2 border-t border-white/10 pt-5 text-xs text-white/35"><ShieldCheck size={14} /> {t('demoReady')}</div></PageContainer></div>
}
