-- Keep newly generated demo/request codes visible to the administrator.
-- Apply after admin_visible_access_code.sql and the demo/payment migrations.

alter table public.dj_accounts add column if not exists access_code_display text;

create or replace function public.sync_dj_access_code_display()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if nullif(trim(coalesce(new.access_code_display, '')), '') is null
     and nullif(trim(coalesce(new.demo_code, '')), '') is not null then
    new.access_code_display := new.demo_code;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_sync_dj_access_code_display on public.dj_accounts;
create trigger trg_sync_dj_access_code_display
before insert or update of demo_code, access_code_display on public.dj_accounts
for each row execute function public.sync_dj_access_code_display();

-- Backfill demo accounts created before the visibility column/trigger existed.
update public.dj_accounts
set access_code_display = demo_code
where nullif(trim(coalesce(access_code_display, '')), '') is null
  and nullif(trim(coalesce(demo_code, '')), '') is not null;

-- The admin list must return both demo codes and codes generated by admin actions.
drop function if exists public.admin_list_djs(text);
create function public.admin_list_djs(p_token text)
returns table(
  id uuid, email text, display_name text, role text, approved boolean, blocked boolean,
  plan_type text, plan_started_at timestamptz, plan_expires_at timestamptz,
  days_used integer, days_remaining integer, is_active boolean, generated_code text
)
language plpgsql security definer set search_path=public,extensions as $$
declare a public.dj_accounts;
begin
  select * into a from public._dj_access(p_token);
  if coalesce(a.role,'') <> 'admin' or a.email <> 'djgianfrancoromerodechosica@gmail.com' then
    raise exception 'Admin only';
  end if;
  return query
    select d.id, d.email, d.display_name, d.role, d.approved, d.blocked,
      d.plan_type, d.plan_started_at, d.plan_expires_at,
      case when d.plan_started_at is null then 0 else greatest(0, floor(extract(epoch from least(now(), d.plan_expires_at) - d.plan_started_at) / 86400)::integer) end,
      case when d.plan_expires_at is null then 0 else greatest(0, floor(extract(epoch from d.plan_expires_at - now()) / 86400)::integer) end,
      (d.approved and not d.blocked and (d.role = 'admin' or d.plan_expires_at > now())),
      coalesce(nullif(d.access_code_display, ''), nullif(d.demo_code, ''))
    from public.dj_accounts d
    order by d.created_at desc;
end;
$$;
grant execute on function public.admin_list_djs(text) to anon, authenticated;
